/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZaaNetAdmin,
  IZaaNetAdminInterface,
} from "../../../contracts/ZaaNetNetwork.sol/IZaaNetAdmin";

const _abi = [
  {
    inputs: [],
    name: "emergencyMode",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hostingFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "treasuryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZaaNetAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IZaaNetAdminInterface {
    return new Interface(_abi) as IZaaNetAdminInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZaaNetAdmin {
    return new Contract(address, _abi, runner) as unknown as IZaaNetAdmin;
  }
}
