/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ZaaNetStorageV1 {
  export type NetworkStruct = {
    id: BigNumberish;
    hostAddress: AddressLike;
    pricePerSession: BigNumberish;
    mongoDataId: string;
    isActive: boolean;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type NetworkStructOutput = [
    id: bigint,
    hostAddress: string,
    pricePerSession: bigint,
    mongoDataId: string,
    isActive: boolean,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    id: bigint;
    hostAddress: string;
    pricePerSession: bigint;
    mongoDataId: string;
    isActive: boolean;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface ZaaNetNetworkV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BATCH_SIZE"
      | "MAX_MONGO_DATA_LENGTH"
      | "MAX_NETWORKS_PER_HOST"
      | "MAX_PRICE_PER_SESSION"
      | "MIN_PRICE_PER_SESSION"
      | "REGISTRATION_COOLDOWN"
      | "UPGRADE_INTERFACE_VERSION"
      | "adminContract"
      | "deactivateNetwork"
      | "getActiveHostNetworkCount"
      | "getActiveHostNetworks"
      | "getAllActiveNetworks"
      | "getContractStats"
      | "getCurrentHostingFee"
      | "getHostNetworks"
      | "getHostStats"
      | "getHostedNetworkById"
      | "getNetworksPaginated"
      | "getTreasuryAddress"
      | "initialize"
      | "isHost"
      | "isReentrancyGuardActive"
      | "isRegisteredHost"
      | "lastRegistrationTime"
      | "networkToHost"
      | "owner"
      | "pause"
      | "paused"
      | "proxiableUUID"
      | "registerNetwork"
      | "renounceOwnership"
      | "setAdminContract"
      | "setUsdtContract"
      | "storageContract"
      | "transferOwnership"
      | "unpause"
      | "updateNetwork"
      | "upgradeToAndCall"
      | "usdt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "HostAdded"
      | "HostingFeePaid"
      | "Initialized"
      | "NetworkPriceUpdated"
      | "NetworkRegistered"
      | "NetworkStatusChanged"
      | "NetworkUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_BATCH_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_MONGO_DATA_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_NETWORKS_PER_HOST",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PRICE_PER_SESSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_PRICE_PER_SESSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REGISTRATION_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateNetwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveHostNetworkCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveHostNetworks",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllActiveNetworks",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentHostingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHostNetworks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHostStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHostedNetworkById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworksPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "isHost", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "isReentrancyGuardActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRegisteredHost",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastRegistrationTime",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "networkToHost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerNetwork",
    values: [BigNumberish, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAdminContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUsdtContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storageContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateNetwork",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_BATCH_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_MONGO_DATA_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_NETWORKS_PER_HOST",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PRICE_PER_SESSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_PRICE_PER_SESSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REGISTRATION_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveHostNetworkCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveHostNetworks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllActiveNetworks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentHostingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostNetworks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostedNetworkById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNetworksPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isHost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isReentrancyGuardActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredHost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastRegistrationTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "networkToHost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAdminContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUsdtContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storageContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
}

export namespace HostAddedEvent {
  export type InputTuple = [host: AddressLike];
  export type OutputTuple = [host: string];
  export interface OutputObject {
    host: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HostingFeePaidEvent {
  export type InputTuple = [
    host: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [host: string, amount: bigint, timestamp: bigint];
  export interface OutputObject {
    host: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NetworkPriceUpdatedEvent {
  export type InputTuple = [
    networkId: BigNumberish,
    oldPrice: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [
    networkId: bigint,
    oldPrice: bigint,
    newPrice: bigint
  ];
  export interface OutputObject {
    networkId: bigint;
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NetworkRegisteredEvent {
  export type InputTuple = [
    networkId: BigNumberish,
    hostAddress: AddressLike,
    mongoDataId: string,
    pricePerSession: BigNumberish,
    isActive: boolean,
    hostingFeePaid: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    networkId: bigint,
    hostAddress: string,
    mongoDataId: string,
    pricePerSession: bigint,
    isActive: boolean,
    hostingFeePaid: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    networkId: bigint;
    hostAddress: string;
    mongoDataId: string;
    pricePerSession: bigint;
    isActive: boolean;
    hostingFeePaid: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NetworkStatusChangedEvent {
  export type InputTuple = [
    networkId: BigNumberish,
    oldStatus: boolean,
    newStatus: boolean
  ];
  export type OutputTuple = [
    networkId: bigint,
    oldStatus: boolean,
    newStatus: boolean
  ];
  export interface OutputObject {
    networkId: bigint;
    oldStatus: boolean;
    newStatus: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NetworkUpdatedEvent {
  export type InputTuple = [
    networkId: BigNumberish,
    hostAddress: AddressLike,
    pricePerSession: BigNumberish,
    mongoDataId: string,
    isActive: boolean
  ];
  export type OutputTuple = [
    networkId: bigint,
    hostAddress: string,
    pricePerSession: bigint,
    mongoDataId: string,
    isActive: boolean
  ];
  export interface OutputObject {
    networkId: bigint;
    hostAddress: string;
    pricePerSession: bigint;
    mongoDataId: string;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZaaNetNetworkV1 extends BaseContract {
  connect(runner?: ContractRunner | null): ZaaNetNetworkV1;
  waitForDeployment(): Promise<this>;

  interface: ZaaNetNetworkV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BATCH_SIZE: TypedContractMethod<[], [bigint], "view">;

  MAX_MONGO_DATA_LENGTH: TypedContractMethod<[], [bigint], "view">;

  MAX_NETWORKS_PER_HOST: TypedContractMethod<[], [bigint], "view">;

  MAX_PRICE_PER_SESSION: TypedContractMethod<[], [bigint], "view">;

  MIN_PRICE_PER_SESSION: TypedContractMethod<[], [bigint], "view">;

  REGISTRATION_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  adminContract: TypedContractMethod<[], [string], "view">;

  deactivateNetwork: TypedContractMethod<
    [_networkId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveHostNetworkCount: TypedContractMethod<
    [hostAddress: AddressLike],
    [bigint],
    "view"
  >;

  getActiveHostNetworks: TypedContractMethod<
    [hostAddress: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [ZaaNetStorageV1.NetworkStructOutput[]],
    "view"
  >;

  getAllActiveNetworks: TypedContractMethod<
    [],
    [ZaaNetStorageV1.NetworkStructOutput[]],
    "view"
  >;

  getContractStats: TypedContractMethod<[], [bigint], "view">;

  getCurrentHostingFee: TypedContractMethod<[], [bigint], "view">;

  getHostNetworks: TypedContractMethod<
    [hostAddress: AddressLike],
    [bigint[]],
    "view"
  >;

  getHostStats: TypedContractMethod<
    [hostAddress: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalNetworks: bigint;
        activeNetworks: bigint;
        totalEarnings: bigint;
      }
    ],
    "view"
  >;

  getHostedNetworkById: TypedContractMethod<
    [_networkId: BigNumberish],
    [ZaaNetStorageV1.NetworkStructOutput],
    "view"
  >;

  getNetworksPaginated: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [
      [ZaaNetStorageV1.NetworkStructOutput[], bigint] & {
        networks: ZaaNetStorageV1.NetworkStructOutput[];
        totalCount: bigint;
      }
    ],
    "view"
  >;

  getTreasuryAddress: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      _storageContract: AddressLike,
      _adminContract: AddressLike,
      _usdt: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isHost: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isReentrancyGuardActive: TypedContractMethod<[], [boolean], "view">;

  isRegisteredHost: TypedContractMethod<
    [hostAddress: AddressLike],
    [boolean],
    "view"
  >;

  lastRegistrationTime: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  networkToHost: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerNetwork: TypedContractMethod<
    [_pricePerSession: BigNumberish, _mongoDataId: string, _isActive: boolean],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAdminContract: TypedContractMethod<
    [_newAdminContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setUsdtContract: TypedContractMethod<
    [_newUsdt: AddressLike],
    [void],
    "nonpayable"
  >;

  storageContract: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateNetwork: TypedContractMethod<
    [
      _networkId: BigNumberish,
      _pricePerSession: BigNumberish,
      _isActive: boolean
    ],
    [void],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BATCH_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_MONGO_DATA_LENGTH"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_NETWORKS_PER_HOST"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PRICE_PER_SESSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PRICE_PER_SESSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "REGISTRATION_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "adminContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deactivateNetwork"
  ): TypedContractMethod<[_networkId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveHostNetworkCount"
  ): TypedContractMethod<[hostAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getActiveHostNetworks"
  ): TypedContractMethod<
    [hostAddress: AddressLike, offset: BigNumberish, limit: BigNumberish],
    [ZaaNetStorageV1.NetworkStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllActiveNetworks"
  ): TypedContractMethod<[], [ZaaNetStorageV1.NetworkStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getContractStats"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentHostingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHostNetworks"
  ): TypedContractMethod<[hostAddress: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getHostStats"
  ): TypedContractMethod<
    [hostAddress: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalNetworks: bigint;
        activeNetworks: bigint;
        totalEarnings: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHostedNetworkById"
  ): TypedContractMethod<
    [_networkId: BigNumberish],
    [ZaaNetStorageV1.NetworkStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNetworksPaginated"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [
      [ZaaNetStorageV1.NetworkStructOutput[], bigint] & {
        networks: ZaaNetStorageV1.NetworkStructOutput[];
        totalCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTreasuryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _storageContract: AddressLike,
      _adminContract: AddressLike,
      _usdt: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isHost"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isReentrancyGuardActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRegisteredHost"
  ): TypedContractMethod<[hostAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastRegistrationTime"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "networkToHost"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerNetwork"
  ): TypedContractMethod<
    [_pricePerSession: BigNumberish, _mongoDataId: string, _isActive: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAdminContract"
  ): TypedContractMethod<
    [_newAdminContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUsdtContract"
  ): TypedContractMethod<[_newUsdt: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storageContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateNetwork"
  ): TypedContractMethod<
    [
      _networkId: BigNumberish,
      _pricePerSession: BigNumberish,
      _isActive: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "HostAdded"
  ): TypedContractEvent<
    HostAddedEvent.InputTuple,
    HostAddedEvent.OutputTuple,
    HostAddedEvent.OutputObject
  >;
  getEvent(
    key: "HostingFeePaid"
  ): TypedContractEvent<
    HostingFeePaidEvent.InputTuple,
    HostingFeePaidEvent.OutputTuple,
    HostingFeePaidEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "NetworkPriceUpdated"
  ): TypedContractEvent<
    NetworkPriceUpdatedEvent.InputTuple,
    NetworkPriceUpdatedEvent.OutputTuple,
    NetworkPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NetworkRegistered"
  ): TypedContractEvent<
    NetworkRegisteredEvent.InputTuple,
    NetworkRegisteredEvent.OutputTuple,
    NetworkRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "NetworkStatusChanged"
  ): TypedContractEvent<
    NetworkStatusChangedEvent.InputTuple,
    NetworkStatusChangedEvent.OutputTuple,
    NetworkStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "NetworkUpdated"
  ): TypedContractEvent<
    NetworkUpdatedEvent.InputTuple,
    NetworkUpdatedEvent.OutputTuple,
    NetworkUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "HostAdded(address)": TypedContractEvent<
      HostAddedEvent.InputTuple,
      HostAddedEvent.OutputTuple,
      HostAddedEvent.OutputObject
    >;
    HostAdded: TypedContractEvent<
      HostAddedEvent.InputTuple,
      HostAddedEvent.OutputTuple,
      HostAddedEvent.OutputObject
    >;

    "HostingFeePaid(address,uint256,uint256)": TypedContractEvent<
      HostingFeePaidEvent.InputTuple,
      HostingFeePaidEvent.OutputTuple,
      HostingFeePaidEvent.OutputObject
    >;
    HostingFeePaid: TypedContractEvent<
      HostingFeePaidEvent.InputTuple,
      HostingFeePaidEvent.OutputTuple,
      HostingFeePaidEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "NetworkPriceUpdated(uint256,uint256,uint256)": TypedContractEvent<
      NetworkPriceUpdatedEvent.InputTuple,
      NetworkPriceUpdatedEvent.OutputTuple,
      NetworkPriceUpdatedEvent.OutputObject
    >;
    NetworkPriceUpdated: TypedContractEvent<
      NetworkPriceUpdatedEvent.InputTuple,
      NetworkPriceUpdatedEvent.OutputTuple,
      NetworkPriceUpdatedEvent.OutputObject
    >;

    "NetworkRegistered(uint256,address,string,uint256,bool,uint256,uint256)": TypedContractEvent<
      NetworkRegisteredEvent.InputTuple,
      NetworkRegisteredEvent.OutputTuple,
      NetworkRegisteredEvent.OutputObject
    >;
    NetworkRegistered: TypedContractEvent<
      NetworkRegisteredEvent.InputTuple,
      NetworkRegisteredEvent.OutputTuple,
      NetworkRegisteredEvent.OutputObject
    >;

    "NetworkStatusChanged(uint256,bool,bool)": TypedContractEvent<
      NetworkStatusChangedEvent.InputTuple,
      NetworkStatusChangedEvent.OutputTuple,
      NetworkStatusChangedEvent.OutputObject
    >;
    NetworkStatusChanged: TypedContractEvent<
      NetworkStatusChangedEvent.InputTuple,
      NetworkStatusChangedEvent.OutputTuple,
      NetworkStatusChangedEvent.OutputObject
    >;

    "NetworkUpdated(uint256,address,uint256,string,bool)": TypedContractEvent<
      NetworkUpdatedEvent.InputTuple,
      NetworkUpdatedEvent.OutputTuple,
      NetworkUpdatedEvent.OutputObject
    >;
    NetworkUpdated: TypedContractEvent<
      NetworkUpdatedEvent.InputTuple,
      NetworkUpdatedEvent.OutputTuple,
      NetworkUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
