/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ZaaNetPaymentV1 {
  export type BatchPaymentStruct = {
    contractId: BigNumberish;
    grossAmount: BigNumberish;
    voucherId: BytesLike;
  };

  export type BatchPaymentStructOutput = [
    contractId: bigint,
    grossAmount: bigint,
    voucherId: string
  ] & { contractId: bigint; grossAmount: bigint; voucherId: string };
}

export interface ZaaNetPaymentV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "addTokenToWhitelist"
      | "adminContract"
      | "contractTokenBalance"
      | "dailyWithdrawalLimit"
      | "dailyWithdrawals"
      | "getRemainingDailyLimit"
      | "getTodayWithdrawals"
      | "getWhitelistedTokens"
      | "initialize"
      | "isReentrancyGuardActive"
      | "isTokenWhitelisted"
      | "isVoucherProcessed"
      | "owner"
      | "pause"
      | "paused"
      | "processBatchPayments"
      | "processPayment"
      | "processedVouchers"
      | "proxiableUUID"
      | "registerHostVouchersAndPayFee"
      | "removeTokenFromWhitelist"
      | "renounceOwnership"
      | "rescueERC20"
      | "setDailyWithdrawalLimit"
      | "storageContract"
      | "tokenDecimals"
      | "transferOwnership"
      | "unpause"
      | "upgradeToAndCall"
      | "usdt"
      | "whitelistedTokenList"
      | "whitelistedTokens"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BatchPaymentProcessed"
      | "DailyLimitExceeded"
      | "DailyLimitUpdated"
      | "HostVouchersRegistered"
      | "Initialized"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentProcessed"
      | "TokenWhitelistUpdated"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addTokenToWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "contractTokenBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyWithdrawalLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyWithdrawals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTodayWithdrawals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelistedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isReentrancyGuardActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVoucherProcessed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processBatchPayments",
    values: [ZaaNetPaymentV1.BatchPaymentStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "processPayment",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "processedVouchers",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerHostVouchersAndPayFee",
    values: [BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTokenFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rescueERC20",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyWithdrawalLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "storageContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokenDecimals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "whitelistedTokenList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTokenToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyWithdrawalLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTodayWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelistedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isReentrancyGuardActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVoucherProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processBatchPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processedVouchers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerHostVouchersAndPayFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTokenFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyWithdrawalLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storageContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedTokenList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "whitelistedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace BatchPaymentProcessedEvent {
  export type InputTuple = [
    batchSize: BigNumberish,
    totalAmount: BigNumberish,
    totalPlatformFee: BigNumberish
  ];
  export type OutputTuple = [
    batchSize: bigint,
    totalAmount: bigint,
    totalPlatformFee: bigint
  ];
  export interface OutputObject {
    batchSize: bigint;
    totalAmount: bigint;
    totalPlatformFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyLimitExceededEvent {
  export type InputTuple = [
    treasury: AddressLike,
    attemptedAmount: BigNumberish,
    dailyLimit: BigNumberish,
    alreadyWithdrawn: BigNumberish
  ];
  export type OutputTuple = [
    treasury: string,
    attemptedAmount: bigint,
    dailyLimit: bigint,
    alreadyWithdrawn: bigint
  ];
  export interface OutputObject {
    treasury: string;
    attemptedAmount: bigint;
    dailyLimit: bigint;
    alreadyWithdrawn: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DailyLimitUpdatedEvent {
  export type InputTuple = [
    newLimit: BigNumberish,
    updatedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    newLimit: bigint,
    updatedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    newLimit: bigint;
    updatedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HostVouchersRegisteredEvent {
  export type InputTuple = [
    host: AddressLike,
    tier: BigNumberish,
    voucherCount: BigNumberish,
    totalFee: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    host: string,
    tier: bigint,
    voucherCount: bigint,
    totalFee: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    host: string;
    tier: bigint;
    voucherCount: bigint;
    totalFee: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentProcessedEvent {
  export type InputTuple = [
    voucherId: BytesLike,
    contractId: BigNumberish,
    host: AddressLike,
    payer: AddressLike,
    grossAmount: BigNumberish,
    platformFee: BigNumberish,
    hostAmount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    voucherId: string,
    contractId: bigint,
    host: string,
    payer: string,
    grossAmount: bigint,
    platformFee: bigint,
    hostAmount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    voucherId: string;
    contractId: bigint;
    host: string;
    payer: string;
    grossAmount: bigint;
    platformFee: bigint;
    hostAmount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWhitelistUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    status: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [token: string, status: boolean, timestamp: bigint];
  export interface OutputObject {
    token: string;
    status: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZaaNetPaymentV1 extends BaseContract {
  connect(runner?: ContractRunner | null): ZaaNetPaymentV1;
  waitForDeployment(): Promise<this>;

  interface: ZaaNetPaymentV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  addTokenToWhitelist: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  adminContract: TypedContractMethod<[], [string], "view">;

  contractTokenBalance: TypedContractMethod<[], [bigint], "view">;

  dailyWithdrawalLimit: TypedContractMethod<[], [bigint], "view">;

  dailyWithdrawals: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getRemainingDailyLimit: TypedContractMethod<[], [bigint], "view">;

  getTodayWithdrawals: TypedContractMethod<[], [bigint], "view">;

  getWhitelistedTokens: TypedContractMethod<[], [string[]], "view">;

  initialize: TypedContractMethod<
    [
      _usdt: AddressLike,
      _storageContract: AddressLike,
      _adminContract: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  isReentrancyGuardActive: TypedContractMethod<[], [boolean], "view">;

  isTokenWhitelisted: TypedContractMethod<
    [_token: AddressLike],
    [boolean],
    "view"
  >;

  isVoucherProcessed: TypedContractMethod<
    [_voucherId: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  processBatchPayments: TypedContractMethod<
    [payments: ZaaNetPaymentV1.BatchPaymentStruct[]],
    [void],
    "nonpayable"
  >;

  processPayment: TypedContractMethod<
    [
      _contractId: BigNumberish,
      _grossAmount: BigNumberish,
      _voucherId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  processedVouchers: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  registerHostVouchersAndPayFee: TypedContractMethod<
    [voucherIds: BytesLike[], tier: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeTokenFromWhitelist: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  rescueERC20: TypedContractMethod<
    [_erc20: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDailyWithdrawalLimit: TypedContractMethod<
    [_newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  storageContract: TypedContractMethod<[], [string], "view">;

  tokenDecimals: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  whitelistedTokenList: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  whitelistedTokens: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  withdrawToken: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addTokenToWhitelist"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "contractTokenBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyWithdrawalLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyWithdrawals"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTodayWithdrawals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWhitelistedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _usdt: AddressLike,
      _storageContract: AddressLike,
      _adminContract: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isReentrancyGuardActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTokenWhitelisted"
  ): TypedContractMethod<[_token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVoucherProcessed"
  ): TypedContractMethod<[_voucherId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "processBatchPayments"
  ): TypedContractMethod<
    [payments: ZaaNetPaymentV1.BatchPaymentStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processPayment"
  ): TypedContractMethod<
    [
      _contractId: BigNumberish,
      _grossAmount: BigNumberish,
      _voucherId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processedVouchers"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerHostVouchersAndPayFee"
  ): TypedContractMethod<
    [voucherIds: BytesLike[], tier: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeTokenFromWhitelist"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rescueERC20"
  ): TypedContractMethod<
    [_erc20: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDailyWithdrawalLimit"
  ): TypedContractMethod<[_newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storageContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "tokenDecimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "whitelistedTokenList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "whitelistedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BatchPaymentProcessed"
  ): TypedContractEvent<
    BatchPaymentProcessedEvent.InputTuple,
    BatchPaymentProcessedEvent.OutputTuple,
    BatchPaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "DailyLimitExceeded"
  ): TypedContractEvent<
    DailyLimitExceededEvent.InputTuple,
    DailyLimitExceededEvent.OutputTuple,
    DailyLimitExceededEvent.OutputObject
  >;
  getEvent(
    key: "DailyLimitUpdated"
  ): TypedContractEvent<
    DailyLimitUpdatedEvent.InputTuple,
    DailyLimitUpdatedEvent.OutputTuple,
    DailyLimitUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HostVouchersRegistered"
  ): TypedContractEvent<
    HostVouchersRegisteredEvent.InputTuple,
    HostVouchersRegisteredEvent.OutputTuple,
    HostVouchersRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentProcessed"
  ): TypedContractEvent<
    PaymentProcessedEvent.InputTuple,
    PaymentProcessedEvent.OutputTuple,
    PaymentProcessedEvent.OutputObject
  >;
  getEvent(
    key: "TokenWhitelistUpdated"
  ): TypedContractEvent<
    TokenWhitelistUpdatedEvent.InputTuple,
    TokenWhitelistUpdatedEvent.OutputTuple,
    TokenWhitelistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "BatchPaymentProcessed(uint256,uint256,uint256)": TypedContractEvent<
      BatchPaymentProcessedEvent.InputTuple,
      BatchPaymentProcessedEvent.OutputTuple,
      BatchPaymentProcessedEvent.OutputObject
    >;
    BatchPaymentProcessed: TypedContractEvent<
      BatchPaymentProcessedEvent.InputTuple,
      BatchPaymentProcessedEvent.OutputTuple,
      BatchPaymentProcessedEvent.OutputObject
    >;

    "DailyLimitExceeded(address,uint256,uint256,uint256)": TypedContractEvent<
      DailyLimitExceededEvent.InputTuple,
      DailyLimitExceededEvent.OutputTuple,
      DailyLimitExceededEvent.OutputObject
    >;
    DailyLimitExceeded: TypedContractEvent<
      DailyLimitExceededEvent.InputTuple,
      DailyLimitExceededEvent.OutputTuple,
      DailyLimitExceededEvent.OutputObject
    >;

    "DailyLimitUpdated(uint256,address,uint256)": TypedContractEvent<
      DailyLimitUpdatedEvent.InputTuple,
      DailyLimitUpdatedEvent.OutputTuple,
      DailyLimitUpdatedEvent.OutputObject
    >;
    DailyLimitUpdated: TypedContractEvent<
      DailyLimitUpdatedEvent.InputTuple,
      DailyLimitUpdatedEvent.OutputTuple,
      DailyLimitUpdatedEvent.OutputObject
    >;

    "HostVouchersRegistered(address,uint8,uint256,uint256,uint256)": TypedContractEvent<
      HostVouchersRegisteredEvent.InputTuple,
      HostVouchersRegisteredEvent.OutputTuple,
      HostVouchersRegisteredEvent.OutputObject
    >;
    HostVouchersRegistered: TypedContractEvent<
      HostVouchersRegisteredEvent.InputTuple,
      HostVouchersRegisteredEvent.OutputTuple,
      HostVouchersRegisteredEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentProcessed(bytes32,uint256,address,address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;
    PaymentProcessed: TypedContractEvent<
      PaymentProcessedEvent.InputTuple,
      PaymentProcessedEvent.OutputTuple,
      PaymentProcessedEvent.OutputObject
    >;

    "TokenWhitelistUpdated(address,bool,uint256)": TypedContractEvent<
      TokenWhitelistUpdatedEvent.InputTuple,
      TokenWhitelistUpdatedEvent.OutputTuple,
      TokenWhitelistUpdatedEvent.OutputObject
    >;
    TokenWhitelistUpdated: TypedContractEvent<
      TokenWhitelistUpdatedEvent.InputTuple,
      TokenWhitelistUpdatedEvent.OutputTuple,
      TokenWhitelistUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
