/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ZaaNetStorage {
  export type NetworkStruct = {
    id: BigNumberish;
    hostAddress: AddressLike;
    pricePerSession: BigNumberish;
    mongoDataId: string;
    isActive: boolean;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type NetworkStructOutput = [
    id: bigint,
    hostAddress: string,
    pricePerSession: bigint,
    mongoDataId: string,
    isActive: boolean,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    id: bigint;
    hostAddress: string;
    pricePerSession: bigint;
    mongoDataId: string;
    isActive: boolean;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface ZaaNetStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowedCallers"
      | "clientVoucherFeeEarnings"
      | "emergencyDeactivateNetwork"
      | "getHostEarnings"
      | "getHostNetworks"
      | "getNetwork"
      | "getNetworksPaginated"
      | "hostEarnings"
      | "hostNetworkIds"
      | "hostVoucherFeeEarnings"
      | "increaseClientVoucherFeeEarnings"
      | "increaseHostEarnings"
      | "increaseHostVoucherFeeEarnings"
      | "incrementNetworkId"
      | "networkExists"
      | "networkIdCounter"
      | "networks"
      | "owner"
      | "pause"
      | "paused"
      | "renounceOwnership"
      | "setAllowedCaller"
      | "setAllowedCallers"
      | "setNetwork"
      | "totalSessionPaymentsAmount"
      | "transferOwnership"
      | "unpause"
      | "updateTotalSessionPaymentsAmount"
      | "updateZaanetHostingFeeEarnings"
      | "updateZaanetWithdrawalsAmount"
      | "zaanetHostingFeeEarnings"
      | "zaanetWithdrawalsAmount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AllowedCallerUpdated"
      | "ClientVoucherFeeEarningsUpdated"
      | "HostEarningsUpdated"
      | "HostVoucherFeeEarningsUpdated"
      | "NetworkStored"
      | "NetworkUpdated"
      | "OwnershipTransferred"
      | "Paused"
      | "SessionStored"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowedCallers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clientVoucherFeeEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyDeactivateNetwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHostEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHostNetworks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworksPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hostEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hostNetworkIds",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hostVoucherFeeEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "increaseClientVoucherFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseHostEarnings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseHostVoucherFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementNetworkId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "networkExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "networkIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "networks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedCallers",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setNetwork",
    values: [BigNumberish, ZaaNetStorage.NetworkStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSessionPaymentsAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTotalSessionPaymentsAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateZaanetHostingFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateZaanetWithdrawalsAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "zaanetHostingFeeEarnings",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "zaanetWithdrawalsAmount",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "allowedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "clientVoucherFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyDeactivateNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostNetworks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNetwork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNetworksPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hostEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hostNetworkIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hostVoucherFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseClientVoucherFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseHostEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseHostVoucherFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementNetworkId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "networkExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "networkIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "networks", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNetwork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSessionPaymentsAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTotalSessionPaymentsAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateZaanetHostingFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateZaanetWithdrawalsAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zaanetHostingFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "zaanetWithdrawalsAmount",
    data: BytesLike
  ): Result;
}

export namespace AllowedCallerUpdatedEvent {
  export type InputTuple = [caller: AddressLike, status: boolean];
  export type OutputTuple = [caller: string, status: boolean];
  export interface OutputObject {
    caller: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClientVoucherFeeEarningsUpdatedEvent {
  export type InputTuple = [totalEarned: BigNumberish];
  export type OutputTuple = [totalEarned: bigint];
  export interface OutputObject {
    totalEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HostEarningsUpdatedEvent {
  export type InputTuple = [
    hostAddress: AddressLike,
    totalEarned: BigNumberish
  ];
  export type OutputTuple = [hostAddress: string, totalEarned: bigint];
  export interface OutputObject {
    hostAddress: string;
    totalEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HostVoucherFeeEarningsUpdatedEvent {
  export type InputTuple = [totalEarned: BigNumberish];
  export type OutputTuple = [totalEarned: bigint];
  export interface OutputObject {
    totalEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NetworkStoredEvent {
  export type InputTuple = [
    id: BigNumberish,
    hostAddress: AddressLike,
    pricePerSession: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    hostAddress: string,
    pricePerSession: bigint
  ];
  export interface OutputObject {
    id: bigint;
    hostAddress: string;
    pricePerSession: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NetworkUpdatedEvent {
  export type InputTuple = [id: BigNumberish, hostAddress: AddressLike];
  export type OutputTuple = [id: bigint, hostAddress: string];
  export interface OutputObject {
    id: bigint;
    hostAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SessionStoredEvent {
  export type InputTuple = [
    sessionId: BigNumberish,
    paymentAddress: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    sessionId: bigint,
    paymentAddress: string,
    amount: bigint
  ];
  export interface OutputObject {
    sessionId: bigint;
    paymentAddress: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZaaNetStorage extends BaseContract {
  connect(runner?: ContractRunner | null): ZaaNetStorage;
  waitForDeployment(): Promise<this>;

  interface: ZaaNetStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowedCallers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  clientVoucherFeeEarnings: TypedContractMethod<[], [bigint], "view">;

  emergencyDeactivateNetwork: TypedContractMethod<
    [networkId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getHostEarnings: TypedContractMethod<
    [hostAddress: AddressLike],
    [bigint],
    "view"
  >;

  getHostNetworks: TypedContractMethod<
    [hostAddress: AddressLike],
    [bigint[]],
    "view"
  >;

  getNetwork: TypedContractMethod<
    [id: BigNumberish],
    [ZaaNetStorage.NetworkStructOutput],
    "view"
  >;

  getNetworksPaginated: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [[ZaaNetStorage.NetworkStructOutput[], bigint] & { total: bigint }],
    "view"
  >;

  hostEarnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  hostNetworkIds: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  hostVoucherFeeEarnings: TypedContractMethod<[], [bigint], "view">;

  increaseClientVoucherFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseHostEarnings: TypedContractMethod<
    [hostAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseHostVoucherFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  incrementNetworkId: TypedContractMethod<[], [bigint], "nonpayable">;

  networkExists: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  networkIdCounter: TypedContractMethod<[], [bigint], "view">;

  networks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, boolean, bigint, bigint] & {
        id: bigint;
        hostAddress: string;
        pricePerSession: bigint;
        mongoDataId: string;
        isActive: boolean;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAllowedCaller: TypedContractMethod<
    [_caller: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setAllowedCallers: TypedContractMethod<
    [_callers: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;

  setNetwork: TypedContractMethod<
    [id: BigNumberish, net: ZaaNetStorage.NetworkStruct],
    [void],
    "nonpayable"
  >;

  totalSessionPaymentsAmount: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateTotalSessionPaymentsAmount: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateZaanetHostingFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateZaanetWithdrawalsAmount: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  zaanetHostingFeeEarnings: TypedContractMethod<[], [bigint], "view">;

  zaanetWithdrawalsAmount: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowedCallers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "clientVoucherFeeEarnings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyDeactivateNetwork"
  ): TypedContractMethod<[networkId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getHostEarnings"
  ): TypedContractMethod<[hostAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHostNetworks"
  ): TypedContractMethod<[hostAddress: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getNetwork"
  ): TypedContractMethod<
    [id: BigNumberish],
    [ZaaNetStorage.NetworkStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNetworksPaginated"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [[ZaaNetStorage.NetworkStructOutput[], bigint] & { total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hostEarnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hostNetworkIds"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "hostVoucherFeeEarnings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "increaseClientVoucherFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "increaseHostEarnings"
  ): TypedContractMethod<
    [hostAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "increaseHostVoucherFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "incrementNetworkId"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "networkExists"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "networkIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "networks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, string, boolean, bigint, bigint] & {
        id: bigint;
        hostAddress: string;
        pricePerSession: bigint;
        mongoDataId: string;
        isActive: boolean;
        createdAt: bigint;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAllowedCaller"
  ): TypedContractMethod<
    [_caller: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowedCallers"
  ): TypedContractMethod<
    [_callers: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setNetwork"
  ): TypedContractMethod<
    [id: BigNumberish, net: ZaaNetStorage.NetworkStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalSessionPaymentsAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTotalSessionPaymentsAmount"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateZaanetHostingFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateZaanetWithdrawalsAmount"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "zaanetHostingFeeEarnings"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "zaanetWithdrawalsAmount"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AllowedCallerUpdated"
  ): TypedContractEvent<
    AllowedCallerUpdatedEvent.InputTuple,
    AllowedCallerUpdatedEvent.OutputTuple,
    AllowedCallerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ClientVoucherFeeEarningsUpdated"
  ): TypedContractEvent<
    ClientVoucherFeeEarningsUpdatedEvent.InputTuple,
    ClientVoucherFeeEarningsUpdatedEvent.OutputTuple,
    ClientVoucherFeeEarningsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HostEarningsUpdated"
  ): TypedContractEvent<
    HostEarningsUpdatedEvent.InputTuple,
    HostEarningsUpdatedEvent.OutputTuple,
    HostEarningsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HostVoucherFeeEarningsUpdated"
  ): TypedContractEvent<
    HostVoucherFeeEarningsUpdatedEvent.InputTuple,
    HostVoucherFeeEarningsUpdatedEvent.OutputTuple,
    HostVoucherFeeEarningsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "NetworkStored"
  ): TypedContractEvent<
    NetworkStoredEvent.InputTuple,
    NetworkStoredEvent.OutputTuple,
    NetworkStoredEvent.OutputObject
  >;
  getEvent(
    key: "NetworkUpdated"
  ): TypedContractEvent<
    NetworkUpdatedEvent.InputTuple,
    NetworkUpdatedEvent.OutputTuple,
    NetworkUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SessionStored"
  ): TypedContractEvent<
    SessionStoredEvent.InputTuple,
    SessionStoredEvent.OutputTuple,
    SessionStoredEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AllowedCallerUpdated(address,bool)": TypedContractEvent<
      AllowedCallerUpdatedEvent.InputTuple,
      AllowedCallerUpdatedEvent.OutputTuple,
      AllowedCallerUpdatedEvent.OutputObject
    >;
    AllowedCallerUpdated: TypedContractEvent<
      AllowedCallerUpdatedEvent.InputTuple,
      AllowedCallerUpdatedEvent.OutputTuple,
      AllowedCallerUpdatedEvent.OutputObject
    >;

    "ClientVoucherFeeEarningsUpdated(uint256)": TypedContractEvent<
      ClientVoucherFeeEarningsUpdatedEvent.InputTuple,
      ClientVoucherFeeEarningsUpdatedEvent.OutputTuple,
      ClientVoucherFeeEarningsUpdatedEvent.OutputObject
    >;
    ClientVoucherFeeEarningsUpdated: TypedContractEvent<
      ClientVoucherFeeEarningsUpdatedEvent.InputTuple,
      ClientVoucherFeeEarningsUpdatedEvent.OutputTuple,
      ClientVoucherFeeEarningsUpdatedEvent.OutputObject
    >;

    "HostEarningsUpdated(address,uint256)": TypedContractEvent<
      HostEarningsUpdatedEvent.InputTuple,
      HostEarningsUpdatedEvent.OutputTuple,
      HostEarningsUpdatedEvent.OutputObject
    >;
    HostEarningsUpdated: TypedContractEvent<
      HostEarningsUpdatedEvent.InputTuple,
      HostEarningsUpdatedEvent.OutputTuple,
      HostEarningsUpdatedEvent.OutputObject
    >;

    "HostVoucherFeeEarningsUpdated(uint256)": TypedContractEvent<
      HostVoucherFeeEarningsUpdatedEvent.InputTuple,
      HostVoucherFeeEarningsUpdatedEvent.OutputTuple,
      HostVoucherFeeEarningsUpdatedEvent.OutputObject
    >;
    HostVoucherFeeEarningsUpdated: TypedContractEvent<
      HostVoucherFeeEarningsUpdatedEvent.InputTuple,
      HostVoucherFeeEarningsUpdatedEvent.OutputTuple,
      HostVoucherFeeEarningsUpdatedEvent.OutputObject
    >;

    "NetworkStored(uint256,address,uint256)": TypedContractEvent<
      NetworkStoredEvent.InputTuple,
      NetworkStoredEvent.OutputTuple,
      NetworkStoredEvent.OutputObject
    >;
    NetworkStored: TypedContractEvent<
      NetworkStoredEvent.InputTuple,
      NetworkStoredEvent.OutputTuple,
      NetworkStoredEvent.OutputObject
    >;

    "NetworkUpdated(uint256,address)": TypedContractEvent<
      NetworkUpdatedEvent.InputTuple,
      NetworkUpdatedEvent.OutputTuple,
      NetworkUpdatedEvent.OutputObject
    >;
    NetworkUpdated: TypedContractEvent<
      NetworkUpdatedEvent.InputTuple,
      NetworkUpdatedEvent.OutputTuple,
      NetworkUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SessionStored(uint256,address,uint256)": TypedContractEvent<
      SessionStoredEvent.InputTuple,
      SessionStoredEvent.OutputTuple,
      SessionStoredEvent.OutputObject
    >;
    SessionStored: TypedContractEvent<
      SessionStoredEvent.InputTuple,
      SessionStoredEvent.OutputTuple,
      SessionStoredEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
