/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ZaaNetAdminV1 {
  export type FeeChangeStruct = {
    oldFee: BigNumberish;
    newFee: BigNumberish;
    timestamp: BigNumberish;
    changedBy: AddressLike;
  };

  export type FeeChangeStructOutput = [
    oldFee: bigint,
    newFee: bigint,
    timestamp: bigint,
    changedBy: string
  ] & { oldFee: bigint; newFee: bigint; timestamp: bigint; changedBy: string };

  export type HostingFeeChangeStruct = {
    oldFee: BigNumberish;
    newFee: BigNumberish;
    timestamp: BigNumberish;
    changedBy: AddressLike;
  };

  export type HostingFeeChangeStructOutput = [
    oldFee: bigint,
    newFee: bigint,
    timestamp: bigint,
    changedBy: string
  ] & { oldFee: bigint; newFee: bigint; timestamp: bigint; changedBy: string };

  export type TreasuryChangeStruct = {
    oldTreasury: AddressLike;
    newTreasury: AddressLike;
    timestamp: BigNumberish;
    changedBy: AddressLike;
  };

  export type TreasuryChangeStructOutput = [
    oldTreasury: string,
    newTreasury: string,
    timestamp: bigint,
    changedBy: string
  ] & {
    oldTreasury: string;
    newTreasury: string;
    timestamp: bigint;
    changedBy: string;
  };
}

export interface ZaaNetAdminV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "EMERGENCY_COOLDOWN"
      | "MAX_HOSTING_FEE"
      | "MAX_HOST_VOUCHER_FEE"
      | "MAX_PLATFORM_FEE"
      | "UPGRADE_INTERFACE_VERSION"
      | "admin"
      | "calculatePlatformFee"
      | "emergencyDeactivateNetwork"
      | "emergencyMode"
      | "emergencyOperators"
      | "emergencySetHostingFee"
      | "emergencySetPlatformFee"
      | "feeHistory"
      | "getAdminStats"
      | "getCurrentFees"
      | "getFeeHistory"
      | "getHostVoucherFeeTier"
      | "getHostingFeeHistory"
      | "getLatestFeeChange"
      | "getLatestHostingFeeChange"
      | "getLatestTreasuryChange"
      | "getPlatformFeeBasisPoints"
      | "getTreasuryHistory"
      | "hostVoucherFeeDays"
      | "hostVoucherFeeHours"
      | "hostVoucherFeeMonths"
      | "hostingFee"
      | "hostingFeeHistory"
      | "initialize"
      | "isEmergencyOperator"
      | "isReentrancyGuardActive"
      | "lastEmergencyToggleBy"
      | "lastEmergencyToggleTime"
      | "owner"
      | "pause"
      | "paused"
      | "payment"
      | "paymentAddress"
      | "platformFeePercent"
      | "proxiableUUID"
      | "renounceOwnership"
      | "setEmergencyOperator"
      | "setHostVoucherFeeDays"
      | "setHostVoucherFeeHours"
      | "setHostVoucherFeeMonths"
      | "setHostingFee"
      | "setPaymentAddress"
      | "setPlatformFee"
      | "setTreasuryAddress"
      | "storageContract"
      | "toggleEmergencyMode"
      | "transferOwnership"
      | "treasury"
      | "treasuryAddress"
      | "treasuryHistory"
      | "unpause"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminPaused"
      | "AdminUnpaused"
      | "ContractsInitialized"
      | "EmergencyModeToggled"
      | "EmergencyOperatorUpdated"
      | "HostVoucherFeeTierUpdated"
      | "HostingFeeUpdated"
      | "Initialized"
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentAddressUpdated"
      | "PlatformFeeUpdated"
      | "TreasuryUpdated"
      | "Unpaused"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "EMERGENCY_COOLDOWN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_HOSTING_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_HOST_VOUCHER_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_PLATFORM_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculatePlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyDeactivateNetwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyOperators",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencySetHostingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencySetPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeHistory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHostVoucherFeeTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHostingFeeHistory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestFeeChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestHostingFeeChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestTreasuryChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFeeBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTreasuryHistory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hostVoucherFeeDays",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hostVoucherFeeHours",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hostVoucherFeeMonths",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hostingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hostingFeeHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isEmergencyOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isReentrancyGuardActive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastEmergencyToggleBy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastEmergencyToggleTime",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "payment", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setHostVoucherFeeDays",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHostVoucherFeeHours",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHostVoucherFeeMonths",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHostingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storageContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "toggleEmergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "treasuryHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "EMERGENCY_COOLDOWN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_HOSTING_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_HOST_VOUCHER_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_PLATFORM_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyDeactivateNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyOperators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencySetHostingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencySetPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeHistory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAdminStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostVoucherFeeTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostingFeeHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestFeeChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestHostingFeeChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestTreasuryChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFeeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTreasuryHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hostVoucherFeeDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hostVoucherFeeHours",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hostVoucherFeeMonths",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hostingFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "hostingFeeHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEmergencyOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isReentrancyGuardActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastEmergencyToggleBy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastEmergencyToggleTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payment", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHostVoucherFeeDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHostVoucherFeeHours",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHostVoucherFeeMonths",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHostingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storageContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "treasuryHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace AdminPausedEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminUnpausedEvent {
  export type InputTuple = [triggeredBy: AddressLike];
  export type OutputTuple = [triggeredBy: string];
  export interface OutputObject {
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ContractsInitializedEvent {
  export type InputTuple = [
    storageContract: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [storageContract: string, timestamp: bigint];
  export interface OutputObject {
    storageContract: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyModeToggledEvent {
  export type InputTuple = [enabled: boolean, triggeredBy: AddressLike];
  export type OutputTuple = [enabled: boolean, triggeredBy: string];
  export interface OutputObject {
    enabled: boolean;
    triggeredBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyOperatorUpdatedEvent {
  export type InputTuple = [
    operator: AddressLike,
    status: boolean,
    updatedBy: AddressLike
  ];
  export type OutputTuple = [
    operator: string,
    status: boolean,
    updatedBy: string
  ];
  export interface OutputObject {
    operator: string;
    status: boolean;
    updatedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HostVoucherFeeTierUpdatedEvent {
  export type InputTuple = [
    tier: BigNumberish,
    newFee: BigNumberish,
    changedBy: AddressLike
  ];
  export type OutputTuple = [tier: bigint, newFee: bigint, changedBy: string];
  export interface OutputObject {
    tier: bigint;
    newFee: bigint;
    changedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HostingFeeUpdatedEvent {
  export type InputTuple = [
    oldFee: BigNumberish,
    newFee: BigNumberish,
    changedBy: AddressLike
  ];
  export type OutputTuple = [oldFee: bigint, newFee: bigint, changedBy: string];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
    changedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentAddressUpdatedEvent {
  export type InputTuple = [
    oldAddress: AddressLike,
    newAddress: AddressLike,
    changedBy: AddressLike
  ];
  export type OutputTuple = [
    oldAddress: string,
    newAddress: string,
    changedBy: string
  ];
  export interface OutputObject {
    oldAddress: string;
    newAddress: string;
    changedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlatformFeeUpdatedEvent {
  export type InputTuple = [
    oldFee: BigNumberish,
    newFee: BigNumberish,
    changedBy: AddressLike
  ];
  export type OutputTuple = [oldFee: bigint, newFee: bigint, changedBy: string];
  export interface OutputObject {
    oldFee: bigint;
    newFee: bigint;
    changedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasuryUpdatedEvent {
  export type InputTuple = [
    oldTreasury: AddressLike,
    newTreasury: AddressLike,
    changedBy: AddressLike
  ];
  export type OutputTuple = [
    oldTreasury: string,
    newTreasury: string,
    changedBy: string
  ];
  export interface OutputObject {
    oldTreasury: string;
    newTreasury: string;
    changedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ZaaNetAdminV1 extends BaseContract {
  connect(runner?: ContractRunner | null): ZaaNetAdminV1;
  waitForDeployment(): Promise<this>;

  interface: ZaaNetAdminV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  EMERGENCY_COOLDOWN: TypedContractMethod<[], [bigint], "view">;

  MAX_HOSTING_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_HOST_VOUCHER_FEE: TypedContractMethod<[], [bigint], "view">;

  MAX_PLATFORM_FEE: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  calculatePlatformFee: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  emergencyDeactivateNetwork: TypedContractMethod<
    [networkId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyMode: TypedContractMethod<[], [boolean], "view">;

  emergencyOperators: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  emergencySetHostingFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencySetPlatformFee: TypedContractMethod<
    [_newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        oldFee: bigint;
        newFee: bigint;
        timestamp: bigint;
        changedBy: string;
      }
    ],
    "view"
  >;

  getAdminStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint, string] & {
        totalFeeChanges: bigint;
        totalTreasuryChanges: bigint;
        totalHostingFeeChanges: bigint;
        isEmergencyMode: boolean;
        currentPlatformFee: bigint;
        currentHostingFee: bigint;
        currentTreasury: string;
      }
    ],
    "view"
  >;

  getCurrentFees: TypedContractMethod<
    [],
    [
      [bigint, bigint, string] & {
        platformFeePercentage: bigint;
        hostingFeeAmount: bigint;
        currentTreasury: string;
      }
    ],
    "view"
  >;

  getFeeHistory: TypedContractMethod<
    [],
    [ZaaNetAdminV1.FeeChangeStructOutput[]],
    "view"
  >;

  getHostVoucherFeeTier: TypedContractMethod<
    [tier: BigNumberish],
    [bigint],
    "view"
  >;

  getHostingFeeHistory: TypedContractMethod<
    [],
    [ZaaNetAdminV1.HostingFeeChangeStructOutput[]],
    "view"
  >;

  getLatestFeeChange: TypedContractMethod<
    [],
    [ZaaNetAdminV1.FeeChangeStructOutput],
    "view"
  >;

  getLatestHostingFeeChange: TypedContractMethod<
    [],
    [ZaaNetAdminV1.HostingFeeChangeStructOutput],
    "view"
  >;

  getLatestTreasuryChange: TypedContractMethod<
    [],
    [ZaaNetAdminV1.TreasuryChangeStructOutput],
    "view"
  >;

  getPlatformFeeBasisPoints: TypedContractMethod<[], [bigint], "view">;

  getTreasuryHistory: TypedContractMethod<
    [],
    [ZaaNetAdminV1.TreasuryChangeStructOutput[]],
    "view"
  >;

  hostVoucherFeeDays: TypedContractMethod<[], [bigint], "view">;

  hostVoucherFeeHours: TypedContractMethod<[], [bigint], "view">;

  hostVoucherFeeMonths: TypedContractMethod<[], [bigint], "view">;

  hostingFee: TypedContractMethod<[], [bigint], "view">;

  hostingFeeHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        oldFee: bigint;
        newFee: bigint;
        timestamp: bigint;
        changedBy: string;
      }
    ],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _storageContract: AddressLike,
      _treasuryAddress: AddressLike,
      _paymentAddress: AddressLike,
      _platformFeePercent: BigNumberish,
      _hostingFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isEmergencyOperator: TypedContractMethod<
    [operator: AddressLike],
    [boolean],
    "view"
  >;

  isReentrancyGuardActive: TypedContractMethod<[], [boolean], "view">;

  lastEmergencyToggleBy: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  lastEmergencyToggleTime: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  payment: TypedContractMethod<[], [string], "view">;

  paymentAddress: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setEmergencyOperator: TypedContractMethod<
    [operator: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setHostVoucherFeeDays: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHostVoucherFeeHours: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHostVoucherFeeMonths: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHostingFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaymentAddress: TypedContractMethod<
    [_newPaymentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasuryAddress: TypedContractMethod<
    [_newTreasuryAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  storageContract: TypedContractMethod<[], [string], "view">;

  toggleEmergencyMode: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  treasuryAddress: TypedContractMethod<[], [string], "view">;

  treasuryHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        oldTreasury: string;
        newTreasury: string;
        timestamp: bigint;
        changedBy: string;
      }
    ],
    "view"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "EMERGENCY_COOLDOWN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_HOSTING_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_HOST_VOUCHER_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_PLATFORM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculatePlatformFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyDeactivateNetwork"
  ): TypedContractMethod<[networkId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencyOperators"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencySetHostingFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencySetPlatformFee"
  ): TypedContractMethod<[_newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "feeHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        oldFee: bigint;
        newFee: bigint;
        timestamp: bigint;
        changedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAdminStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint, string] & {
        totalFeeChanges: bigint;
        totalTreasuryChanges: bigint;
        totalHostingFeeChanges: bigint;
        isEmergencyMode: boolean;
        currentPlatformFee: bigint;
        currentHostingFee: bigint;
        currentTreasury: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentFees"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string] & {
        platformFeePercentage: bigint;
        hostingFeeAmount: bigint;
        currentTreasury: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeeHistory"
  ): TypedContractMethod<[], [ZaaNetAdminV1.FeeChangeStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getHostVoucherFeeTier"
  ): TypedContractMethod<[tier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHostingFeeHistory"
  ): TypedContractMethod<
    [],
    [ZaaNetAdminV1.HostingFeeChangeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestFeeChange"
  ): TypedContractMethod<[], [ZaaNetAdminV1.FeeChangeStructOutput], "view">;
  getFunction(
    nameOrSignature: "getLatestHostingFeeChange"
  ): TypedContractMethod<
    [],
    [ZaaNetAdminV1.HostingFeeChangeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLatestTreasuryChange"
  ): TypedContractMethod<
    [],
    [ZaaNetAdminV1.TreasuryChangeStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlatformFeeBasisPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTreasuryHistory"
  ): TypedContractMethod<
    [],
    [ZaaNetAdminV1.TreasuryChangeStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hostVoucherFeeDays"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hostVoucherFeeHours"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hostVoucherFeeMonths"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hostingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hostingFeeHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        oldFee: bigint;
        newFee: bigint;
        timestamp: bigint;
        changedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _storageContract: AddressLike,
      _treasuryAddress: AddressLike,
      _paymentAddress: AddressLike,
      _platformFeePercent: BigNumberish,
      _hostingFee: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isEmergencyOperator"
  ): TypedContractMethod<[operator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isReentrancyGuardActive"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastEmergencyToggleBy"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastEmergencyToggleTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "payment"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEmergencyOperator"
  ): TypedContractMethod<
    [operator: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHostVoucherFeeDays"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHostVoucherFeeHours"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHostVoucherFeeMonths"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHostingFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentAddress"
  ): TypedContractMethod<
    [_newPaymentAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasuryAddress"
  ): TypedContractMethod<
    [_newTreasuryAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "storageContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "toggleEmergencyMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasuryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasuryHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, string] & {
        oldTreasury: string;
        newTreasury: string;
        timestamp: bigint;
        changedBy: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "AdminPaused"
  ): TypedContractEvent<
    AdminPausedEvent.InputTuple,
    AdminPausedEvent.OutputTuple,
    AdminPausedEvent.OutputObject
  >;
  getEvent(
    key: "AdminUnpaused"
  ): TypedContractEvent<
    AdminUnpausedEvent.InputTuple,
    AdminUnpausedEvent.OutputTuple,
    AdminUnpausedEvent.OutputObject
  >;
  getEvent(
    key: "ContractsInitialized"
  ): TypedContractEvent<
    ContractsInitializedEvent.InputTuple,
    ContractsInitializedEvent.OutputTuple,
    ContractsInitializedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyModeToggled"
  ): TypedContractEvent<
    EmergencyModeToggledEvent.InputTuple,
    EmergencyModeToggledEvent.OutputTuple,
    EmergencyModeToggledEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyOperatorUpdated"
  ): TypedContractEvent<
    EmergencyOperatorUpdatedEvent.InputTuple,
    EmergencyOperatorUpdatedEvent.OutputTuple,
    EmergencyOperatorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HostVoucherFeeTierUpdated"
  ): TypedContractEvent<
    HostVoucherFeeTierUpdatedEvent.InputTuple,
    HostVoucherFeeTierUpdatedEvent.OutputTuple,
    HostVoucherFeeTierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "HostingFeeUpdated"
  ): TypedContractEvent<
    HostingFeeUpdatedEvent.InputTuple,
    HostingFeeUpdatedEvent.OutputTuple,
    HostingFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentAddressUpdated"
  ): TypedContractEvent<
    PaymentAddressUpdatedEvent.InputTuple,
    PaymentAddressUpdatedEvent.OutputTuple,
    PaymentAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PlatformFeeUpdated"
  ): TypedContractEvent<
    PlatformFeeUpdatedEvent.InputTuple,
    PlatformFeeUpdatedEvent.OutputTuple,
    PlatformFeeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TreasuryUpdated"
  ): TypedContractEvent<
    TreasuryUpdatedEvent.InputTuple,
    TreasuryUpdatedEvent.OutputTuple,
    TreasuryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "AdminPaused(address)": TypedContractEvent<
      AdminPausedEvent.InputTuple,
      AdminPausedEvent.OutputTuple,
      AdminPausedEvent.OutputObject
    >;
    AdminPaused: TypedContractEvent<
      AdminPausedEvent.InputTuple,
      AdminPausedEvent.OutputTuple,
      AdminPausedEvent.OutputObject
    >;

    "AdminUnpaused(address)": TypedContractEvent<
      AdminUnpausedEvent.InputTuple,
      AdminUnpausedEvent.OutputTuple,
      AdminUnpausedEvent.OutputObject
    >;
    AdminUnpaused: TypedContractEvent<
      AdminUnpausedEvent.InputTuple,
      AdminUnpausedEvent.OutputTuple,
      AdminUnpausedEvent.OutputObject
    >;

    "ContractsInitialized(address,uint256)": TypedContractEvent<
      ContractsInitializedEvent.InputTuple,
      ContractsInitializedEvent.OutputTuple,
      ContractsInitializedEvent.OutputObject
    >;
    ContractsInitialized: TypedContractEvent<
      ContractsInitializedEvent.InputTuple,
      ContractsInitializedEvent.OutputTuple,
      ContractsInitializedEvent.OutputObject
    >;

    "EmergencyModeToggled(bool,address)": TypedContractEvent<
      EmergencyModeToggledEvent.InputTuple,
      EmergencyModeToggledEvent.OutputTuple,
      EmergencyModeToggledEvent.OutputObject
    >;
    EmergencyModeToggled: TypedContractEvent<
      EmergencyModeToggledEvent.InputTuple,
      EmergencyModeToggledEvent.OutputTuple,
      EmergencyModeToggledEvent.OutputObject
    >;

    "EmergencyOperatorUpdated(address,bool,address)": TypedContractEvent<
      EmergencyOperatorUpdatedEvent.InputTuple,
      EmergencyOperatorUpdatedEvent.OutputTuple,
      EmergencyOperatorUpdatedEvent.OutputObject
    >;
    EmergencyOperatorUpdated: TypedContractEvent<
      EmergencyOperatorUpdatedEvent.InputTuple,
      EmergencyOperatorUpdatedEvent.OutputTuple,
      EmergencyOperatorUpdatedEvent.OutputObject
    >;

    "HostVoucherFeeTierUpdated(uint8,uint256,address)": TypedContractEvent<
      HostVoucherFeeTierUpdatedEvent.InputTuple,
      HostVoucherFeeTierUpdatedEvent.OutputTuple,
      HostVoucherFeeTierUpdatedEvent.OutputObject
    >;
    HostVoucherFeeTierUpdated: TypedContractEvent<
      HostVoucherFeeTierUpdatedEvent.InputTuple,
      HostVoucherFeeTierUpdatedEvent.OutputTuple,
      HostVoucherFeeTierUpdatedEvent.OutputObject
    >;

    "HostingFeeUpdated(uint256,uint256,address)": TypedContractEvent<
      HostingFeeUpdatedEvent.InputTuple,
      HostingFeeUpdatedEvent.OutputTuple,
      HostingFeeUpdatedEvent.OutputObject
    >;
    HostingFeeUpdated: TypedContractEvent<
      HostingFeeUpdatedEvent.InputTuple,
      HostingFeeUpdatedEvent.OutputTuple,
      HostingFeeUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentAddressUpdated(address,address,address)": TypedContractEvent<
      PaymentAddressUpdatedEvent.InputTuple,
      PaymentAddressUpdatedEvent.OutputTuple,
      PaymentAddressUpdatedEvent.OutputObject
    >;
    PaymentAddressUpdated: TypedContractEvent<
      PaymentAddressUpdatedEvent.InputTuple,
      PaymentAddressUpdatedEvent.OutputTuple,
      PaymentAddressUpdatedEvent.OutputObject
    >;

    "PlatformFeeUpdated(uint256,uint256,address)": TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;
    PlatformFeeUpdated: TypedContractEvent<
      PlatformFeeUpdatedEvent.InputTuple,
      PlatformFeeUpdatedEvent.OutputTuple,
      PlatformFeeUpdatedEvent.OutputObject
    >;

    "TreasuryUpdated(address,address,address)": TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;
    TreasuryUpdated: TypedContractEvent<
      TreasuryUpdatedEvent.InputTuple,
      TreasuryUpdatedEvent.OutputTuple,
      TreasuryUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
