/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZaaNetNetwork,
  IZaaNetNetworkInterface,
} from "../../../contracts/interface/IZaaNetNetwork";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "networkId",
        type: "uint256",
      },
    ],
    name: "deactivateNetwork",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hostAddress",
        type: "address",
      },
    ],
    name: "getActiveHostNetworkCount",
    outputs: [
      {
        internalType: "uint256",
        name: "count",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hostAddress",
        type: "address",
      },
    ],
    name: "getActiveHostNetworks",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "hostAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "pricePerSession",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "mongoDataId",
            type: "string",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "updatedAt",
            type: "uint256",
          },
        ],
        internalType: "struct IZaaNetStorage.Network[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hostAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getActiveHostNetworks",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "hostAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "pricePerSession",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "mongoDataId",
            type: "string",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "updatedAt",
            type: "uint256",
          },
        ],
        internalType: "struct IZaaNetStorage.Network[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllActiveNetworks",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "hostAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "pricePerSession",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "mongoDataId",
            type: "string",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "updatedAt",
            type: "uint256",
          },
        ],
        internalType: "struct IZaaNetStorage.Network[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getContractStats",
    outputs: [
      {
        internalType: "uint256",
        name: "totalNetworks",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getCurrentHostingFee",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hostAddress",
        type: "address",
      },
    ],
    name: "getHostNetworks",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hostAddress",
        type: "address",
      },
    ],
    name: "getHostStats",
    outputs: [
      {
        internalType: "uint256",
        name: "totalNetworks",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "activeNetworks",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalEarnings",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "networkId",
        type: "uint256",
      },
    ],
    name: "getHostedNetworkById",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "hostAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "pricePerSession",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "mongoDataId",
            type: "string",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "updatedAt",
            type: "uint256",
          },
        ],
        internalType: "struct IZaaNetStorage.Network",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "offset",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "limit",
        type: "uint256",
      },
    ],
    name: "getNetworksPaginated",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "id",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "hostAddress",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "pricePerSession",
            type: "uint256",
          },
          {
            internalType: "string",
            name: "mongoDataId",
            type: "string",
          },
          {
            internalType: "bool",
            name: "isActive",
            type: "bool",
          },
          {
            internalType: "uint256",
            name: "createdAt",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "updatedAt",
            type: "uint256",
          },
        ],
        internalType: "struct IZaaNetStorage.Network[]",
        name: "networks",
        type: "tuple[]",
      },
      {
        internalType: "uint256",
        name: "totalCount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTreasuryAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "hostAddress",
        type: "address",
      },
    ],
    name: "isRegisteredHost",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "pricePerSession",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "mongoDataId",
        type: "string",
      },
      {
        internalType: "bool",
        name: "isActive",
        type: "bool",
      },
    ],
    name: "registerNetwork",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newAdminContract",
        type: "address",
      },
    ],
    name: "setAdminContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newUsdt",
        type: "address",
      },
    ],
    name: "setUsdtContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "networkId",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "pricePerSession",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isActive",
        type: "bool",
      },
    ],
    name: "updateNetwork",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IZaaNetNetwork__factory {
  static readonly abi = _abi;
  static createInterface(): IZaaNetNetworkInterface {
    return new Interface(_abi) as IZaaNetNetworkInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZaaNetNetwork {
    return new Contract(address, _abi, runner) as unknown as IZaaNetNetwork;
  }
}
