/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IZaaNetStorage {
  export type NetworkStruct = {
    id: BigNumberish;
    hostAddress: AddressLike;
    pricePerSession: BigNumberish;
    mongoDataId: string;
    isActive: boolean;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type NetworkStructOutput = [
    id: bigint,
    hostAddress: string,
    pricePerSession: bigint,
    mongoDataId: string,
    isActive: boolean,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    id: bigint;
    hostAddress: string;
    pricePerSession: bigint;
    mongoDataId: string;
    isActive: boolean;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface IZaaNetStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getNetwork"
      | "increaseClientVoucherFeeEarnings"
      | "increaseHostEarnings"
      | "increaseHostVoucherFeeEarnings"
      | "updateTotalSessionPaymentsAmount"
      | "updateZaanetHostingFeeEarnings"
      | "updateZaanetWithdrawalsAmount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getNetwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseClientVoucherFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseHostEarnings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseHostVoucherFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTotalSessionPaymentsAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateZaanetHostingFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateZaanetWithdrawalsAmount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getNetwork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "increaseClientVoucherFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseHostEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseHostVoucherFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTotalSessionPaymentsAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateZaanetHostingFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateZaanetWithdrawalsAmount",
    data: BytesLike
  ): Result;
}

export interface IZaaNetStorage extends BaseContract {
  connect(runner?: ContractRunner | null): IZaaNetStorage;
  waitForDeployment(): Promise<this>;

  interface: IZaaNetStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getNetwork: TypedContractMethod<
    [networkId: BigNumberish],
    [IZaaNetStorage.NetworkStructOutput],
    "view"
  >;

  increaseClientVoucherFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseHostEarnings: TypedContractMethod<
    [host: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseHostVoucherFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTotalSessionPaymentsAmount: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateZaanetHostingFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateZaanetWithdrawalsAmount: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getNetwork"
  ): TypedContractMethod<
    [networkId: BigNumberish],
    [IZaaNetStorage.NetworkStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "increaseClientVoucherFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "increaseHostEarnings"
  ): TypedContractMethod<
    [host: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "increaseHostVoucherFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTotalSessionPaymentsAmount"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateZaanetHostingFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateZaanetWithdrawalsAmount"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  filters: {};
}
