/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IZaaNetNetwork,
  IZaaNetNetworkInterface,
} from "../../../contracts/ZaaNetPayment.sol/IZaaNetNetwork";

const _abi = [
  {
    inputs: [],
    name: "MIN_PRICE_PER_SESSION",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IZaaNetNetwork__factory {
  static readonly abi = _abi;
  static createInterface(): IZaaNetNetworkInterface {
    return new Interface(_abi) as IZaaNetNetworkInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IZaaNetNetwork {
    return new Contract(address, _abi, runner) as unknown as IZaaNetNetwork;
  }
}
