/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IZaaNetAdmin } from "./IZaaNetAdmin";
export type { IZaaNetNetwork } from "./IZaaNetNetwork";
export type { IZaaNetPayment } from "./IZaaNetPayment";
export type { IZaaNetStorage } from "./IZaaNetStorage";
