/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IZaaNetStorage {
  export type NetworkStruct = {
    id: BigNumberish;
    hostAddress: AddressLike;
    pricePerSession: BigNumberish;
    mongoDataId: string;
    isActive: boolean;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type NetworkStructOutput = [
    id: bigint,
    hostAddress: string,
    pricePerSession: bigint,
    mongoDataId: string,
    isActive: boolean,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    id: bigint;
    hostAddress: string;
    pricePerSession: bigint;
    mongoDataId: string;
    isActive: boolean;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface IZaaNetStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "emergencyDeactivateNetwork"
      | "getHostEarnings"
      | "getHostNetworkCount"
      | "getHostNetworks"
      | "getNetwork"
      | "getNetworksPaginated"
      | "hasReachedNetworkLimit"
      | "increaseClientVoucherFeeEarnings"
      | "increaseHostEarnings"
      | "increaseHostVoucherFeeEarnings"
      | "incrementNetworkId"
      | "networkIdCounter"
      | "pause"
      | "setAllowedCaller"
      | "setAllowedCallers"
      | "setNetwork"
      | "unpause"
      | "updateTotalSessionPaymentsAmount"
      | "updateZaanetHostingFeeEarnings"
      | "updateZaanetWithdrawalsAmount"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "emergencyDeactivateNetwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHostEarnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHostNetworkCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHostNetworks",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetworksPaginated",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasReachedNetworkLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseClientVoucherFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseHostEarnings",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "increaseHostVoucherFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementNetworkId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "networkIdCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAllowedCaller",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setAllowedCallers",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setNetwork",
    values: [BigNumberish, IZaaNetStorage.NetworkStruct]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateTotalSessionPaymentsAmount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateZaanetHostingFeeEarnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateZaanetWithdrawalsAmount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "emergencyDeactivateNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostNetworkCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostNetworks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNetwork", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getNetworksPaginated",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasReachedNetworkLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseClientVoucherFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseHostEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "increaseHostVoucherFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementNetworkId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "networkIdCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAllowedCallers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNetwork", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTotalSessionPaymentsAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateZaanetHostingFeeEarnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateZaanetWithdrawalsAmount",
    data: BytesLike
  ): Result;
}

export interface IZaaNetStorage extends BaseContract {
  connect(runner?: ContractRunner | null): IZaaNetStorage;
  waitForDeployment(): Promise<this>;

  interface: IZaaNetStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emergencyDeactivateNetwork: TypedContractMethod<
    [networkId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getHostEarnings: TypedContractMethod<
    [hostAddress: AddressLike],
    [bigint],
    "view"
  >;

  getHostNetworkCount: TypedContractMethod<
    [hostAddress: AddressLike],
    [bigint],
    "view"
  >;

  getHostNetworks: TypedContractMethod<
    [hostAddress: AddressLike],
    [bigint[]],
    "view"
  >;

  getNetwork: TypedContractMethod<
    [id: BigNumberish],
    [IZaaNetStorage.NetworkStructOutput],
    "view"
  >;

  getNetworksPaginated: TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [[IZaaNetStorage.NetworkStructOutput[], bigint] & { total: bigint }],
    "view"
  >;

  hasReachedNetworkLimit: TypedContractMethod<
    [hostAddress: AddressLike],
    [boolean],
    "view"
  >;

  increaseClientVoucherFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseHostEarnings: TypedContractMethod<
    [hostAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  increaseHostVoucherFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  incrementNetworkId: TypedContractMethod<[], [bigint], "nonpayable">;

  networkIdCounter: TypedContractMethod<[], [bigint], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  setAllowedCaller: TypedContractMethod<
    [_caller: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setAllowedCallers: TypedContractMethod<
    [_callers: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;

  setNetwork: TypedContractMethod<
    [id: BigNumberish, network: IZaaNetStorage.NetworkStruct],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateTotalSessionPaymentsAmount: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateZaanetHostingFeeEarnings: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateZaanetWithdrawalsAmount: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emergencyDeactivateNetwork"
  ): TypedContractMethod<[networkId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getHostEarnings"
  ): TypedContractMethod<[hostAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHostNetworkCount"
  ): TypedContractMethod<[hostAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getHostNetworks"
  ): TypedContractMethod<[hostAddress: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getNetwork"
  ): TypedContractMethod<
    [id: BigNumberish],
    [IZaaNetStorage.NetworkStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNetworksPaginated"
  ): TypedContractMethod<
    [offset: BigNumberish, limit: BigNumberish],
    [[IZaaNetStorage.NetworkStructOutput[], bigint] & { total: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasReachedNetworkLimit"
  ): TypedContractMethod<[hostAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "increaseClientVoucherFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "increaseHostEarnings"
  ): TypedContractMethod<
    [hostAddress: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "increaseHostVoucherFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "incrementNetworkId"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "networkIdCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAllowedCaller"
  ): TypedContractMethod<
    [_caller: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAllowedCallers"
  ): TypedContractMethod<
    [_callers: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setNetwork"
  ): TypedContractMethod<
    [id: BigNumberish, network: IZaaNetStorage.NetworkStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateTotalSessionPaymentsAmount"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateZaanetHostingFeeEarnings"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateZaanetWithdrawalsAmount"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  filters: {};
}
