/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IZaaNetPayment {
  export type BatchPaymentStruct = {
    contractId: BigNumberish;
    grossAmount: BigNumberish;
    voucherId: BytesLike;
  };

  export type BatchPaymentStructOutput = [
    contractId: bigint,
    grossAmount: bigint,
    voucherId: string
  ] & { contractId: bigint; grossAmount: bigint; voucherId: string };
}

export interface IZaaNetPaymentInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTokenToWhitelist"
      | "contractTokenBalance"
      | "getRemainingDailyLimit"
      | "getTodayWithdrawals"
      | "getWhitelistedTokens"
      | "isTokenWhitelisted"
      | "isVoucherProcessed"
      | "pause"
      | "processBatchPayments"
      | "processPayment"
      | "removeTokenFromWhitelist"
      | "setDailyWithdrawalLimit"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addTokenToWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "contractTokenBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRemainingDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTodayWithdrawals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWhitelistedTokens",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVoucherProcessed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processBatchPayments",
    values: [IZaaNetPayment.BatchPaymentStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "processPayment",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTokenFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDailyWithdrawalLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addTokenToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "contractTokenBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRemainingDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTodayWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWhitelistedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isVoucherProcessed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processBatchPayments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processPayment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTokenFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDailyWithdrawalLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export interface IZaaNetPayment extends BaseContract {
  connect(runner?: ContractRunner | null): IZaaNetPayment;
  waitForDeployment(): Promise<this>;

  interface: IZaaNetPaymentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTokenToWhitelist: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  contractTokenBalance: TypedContractMethod<[], [bigint], "view">;

  getRemainingDailyLimit: TypedContractMethod<[], [bigint], "view">;

  getTodayWithdrawals: TypedContractMethod<[], [bigint], "view">;

  getWhitelistedTokens: TypedContractMethod<[], [string[]], "view">;

  isTokenWhitelisted: TypedContractMethod<
    [_token: AddressLike],
    [boolean],
    "view"
  >;

  isVoucherProcessed: TypedContractMethod<
    [_voucherId: BytesLike],
    [boolean],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  processBatchPayments: TypedContractMethod<
    [payments: IZaaNetPayment.BatchPaymentStruct[]],
    [void],
    "nonpayable"
  >;

  processPayment: TypedContractMethod<
    [
      _contractId: BigNumberish,
      _grossAmount: BigNumberish,
      _voucherId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  removeTokenFromWhitelist: TypedContractMethod<
    [_token: AddressLike],
    [void],
    "nonpayable"
  >;

  setDailyWithdrawalLimit: TypedContractMethod<
    [_newLimit: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTokenToWhitelist"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "contractTokenBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRemainingDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTodayWithdrawals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getWhitelistedTokens"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isTokenWhitelisted"
  ): TypedContractMethod<[_token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isVoucherProcessed"
  ): TypedContractMethod<[_voucherId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "processBatchPayments"
  ): TypedContractMethod<
    [payments: IZaaNetPayment.BatchPaymentStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "processPayment"
  ): TypedContractMethod<
    [
      _contractId: BigNumberish,
      _grossAmount: BigNumberish,
      _voucherId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeTokenFromWhitelist"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDailyWithdrawalLimit"
  ): TypedContractMethod<[_newLimit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
