/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IZaaNetAdminInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "calculatePlatformFee"
      | "emergencyDeactivateNetwork"
      | "emergencyMode"
      | "emergencySetHostingFee"
      | "emergencySetPlatformFee"
      | "getAdminStats"
      | "getCurrentFees"
      | "getHostVoucherFeeTier"
      | "getPlatformFeeBasisPoints"
      | "hostingFee"
      | "isEmergencyOperator"
      | "owner"
      | "pause"
      | "paused"
      | "paymentAddress"
      | "platformFeePercent"
      | "setEmergencyOperator"
      | "setHostVoucherFeeDays"
      | "setHostVoucherFeeHours"
      | "setHostVoucherFeeMonths"
      | "setHostingFee"
      | "setPaymentAddress"
      | "setPlatformFee"
      | "setTreasuryAddress"
      | "toggleEmergencyMode"
      | "treasury"
      | "treasuryAddress"
      | "unpause"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "calculatePlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyDeactivateNetwork",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencySetHostingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencySetPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHostVoucherFeeTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformFeeBasisPoints",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hostingFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isEmergencyOperator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeePercent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyOperator",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setHostVoucherFeeDays",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHostVoucherFeeHours",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHostVoucherFeeMonths",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setHostingFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasuryAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "toggleEmergencyMode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "treasuryAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculatePlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyDeactivateNetwork",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencySetHostingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencySetPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdminStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHostVoucherFeeTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformFeeBasisPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hostingFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isEmergencyOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeePercent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyOperator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHostVoucherFeeDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHostVoucherFeeHours",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHostVoucherFeeMonths",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setHostingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggleEmergencyMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "treasuryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export interface IZaaNetAdmin extends BaseContract {
  connect(runner?: ContractRunner | null): IZaaNetAdmin;
  waitForDeployment(): Promise<this>;

  interface: IZaaNetAdminInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  calculatePlatformFee: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  emergencyDeactivateNetwork: TypedContractMethod<
    [networkId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyMode: TypedContractMethod<[], [boolean], "view">;

  emergencySetHostingFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencySetPlatformFee: TypedContractMethod<
    [_newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAdminStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint, string] & {
        totalFeeChanges: bigint;
        totalTreasuryChanges: bigint;
        totalHostingFeeChanges: bigint;
        isEmergencyMode: boolean;
        currentPlatformFee: bigint;
        currentHostingFee: bigint;
        currentTreasury: string;
      }
    ],
    "view"
  >;

  getCurrentFees: TypedContractMethod<
    [],
    [
      [bigint, bigint, string] & {
        platformFeePercentage: bigint;
        hostingFeeAmount: bigint;
        treasury: string;
      }
    ],
    "view"
  >;

  getHostVoucherFeeTier: TypedContractMethod<
    [tier: BigNumberish],
    [bigint],
    "view"
  >;

  getPlatformFeeBasisPoints: TypedContractMethod<[], [bigint], "view">;

  hostingFee: TypedContractMethod<[], [bigint], "view">;

  isEmergencyOperator: TypedContractMethod<
    [operator: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentAddress: TypedContractMethod<[], [string], "view">;

  platformFeePercent: TypedContractMethod<[], [bigint], "view">;

  setEmergencyOperator: TypedContractMethod<
    [operator: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setHostVoucherFeeDays: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHostVoucherFeeHours: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHostVoucherFeeMonths: TypedContractMethod<
    [_fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setHostingFee: TypedContractMethod<
    [_newFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  setPaymentAddress: TypedContractMethod<
    [_newPaymentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [_newFeePercent: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasuryAddress: TypedContractMethod<
    [_newTreasury: AddressLike],
    [void],
    "nonpayable"
  >;

  toggleEmergencyMode: TypedContractMethod<[], [void], "nonpayable">;

  treasury: TypedContractMethod<[], [string], "view">;

  treasuryAddress: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculatePlatformFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyDeactivateNetwork"
  ): TypedContractMethod<[networkId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyMode"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "emergencySetHostingFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencySetPlatformFee"
  ): TypedContractMethod<[_newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAdminStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean, bigint, bigint, string] & {
        totalFeeChanges: bigint;
        totalTreasuryChanges: bigint;
        totalHostingFeeChanges: bigint;
        isEmergencyMode: boolean;
        currentPlatformFee: bigint;
        currentHostingFee: bigint;
        currentTreasury: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentFees"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, string] & {
        platformFeePercentage: bigint;
        hostingFeeAmount: bigint;
        treasury: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHostVoucherFeeTier"
  ): TypedContractMethod<[tier: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlatformFeeBasisPoints"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "hostingFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isEmergencyOperator"
  ): TypedContractMethod<[operator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeePercent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setEmergencyOperator"
  ): TypedContractMethod<
    [operator: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHostVoucherFeeDays"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHostVoucherFeeHours"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHostVoucherFeeMonths"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setHostingFee"
  ): TypedContractMethod<[_newFee: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentAddress"
  ): TypedContractMethod<
    [_newPaymentAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[_newFeePercent: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasuryAddress"
  ): TypedContractMethod<[_newTreasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "toggleEmergencyMode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "treasuryAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
